services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=itsupportpass
      - APP_USER=db_itsupptickets
      - APP_USER_PASSWORD=itsupportpass
    ports:
      - "1521:1521"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: it-support-backend
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=db_itsupptickets
      - SPRING_DATASOURCE_PASSWORD=itsupportpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
